### ISSUE TITLE
Missing titel and picture of a terraforming tech

### ISSUE THREAD

**Issue by Darcoon** [CoFH/StellarExpansion#3]
So I was just playing my game and then a quite broken looking research showed up.
It basic look like this: http://imgur.com/a/aqejV

not really game breaking but I thought I'd report it.

If you need anything more related to it I'd be glad to help.

**Comment by KingLemming** [comment]
This is because you don't have the correct mods installed. You need Terraforming AND Terraforming (Extreme) - you only have the latter. The Steam page clearly shows this.
